apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: teachlea
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: "quarkus/quarkus-basic-auth-jvm:v1"
          name: my-app
          imagePullPolicy: Never
          ports:
            - name: web
              containerPort: 8080
          envFrom:
            - secretRef:
               name: my-secret