---
openapi: 3.0.3
info:
  title: teachlea openapi specification from static file
  contact:
    name: Example API Support
    url: http://teachlea.com/contact
    email: teachlea.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
paths:
  /hello:
    get:
      tags:
        - Greeting Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
